spring.application.name=bank-account-service
server.port=8082

# H2
spring.datasource.url=jdbc:h2:mem:account-db
spring.h2.console.enabled=true
spring.jpa.show-sql=true


spring.data.rest.base-path=/rest

# GraphQL
spring.graphql.graphiql.enabled=true